gob/jobs/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_required

from gob.jobs.views import (JobListView, JobCreateView, JobUpdateView,
                            JobUserListView)

app_name = 'jobs'
urlpatterns = [
    url(r'^$', JobListView.as_view(), name='jobs'),
    url(r'^add', login_required(JobCreateView.as_view()), name='add'),
    url(r'^self', login_required(JobUserListView.as_view()), name='self'),
    url(r'^edit/(?P<pk>[\w-]+)$', login_required(JobUpdateView.as_view()),
        name='edit'),
    # TODO:
    # Move following to user_manager
    url(r'^login', RedirectView.as_view(
        url=settings.OAUTH_LOGIN_URL, permanent=False), name='login'),
]

gob/urls.py
from importlib import import_module

from django.conf.urls import re_path, include
from django.contrib import admin
from allauth.socialaccount import providers

# Little hack to allow only /accounts/reddit/ and /accounts/slack/ URLs
# from https://github.com/pennersr/django-allauth/blob/0.35.0/allauth/urls.py#L15,#L22  # noqa
prov_urlpatterns = []
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns += getattr(prov_mod, 'urlpatterns', None)


urlpatterns = [
    re_path(r'^', include('gob.jobs.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include(prov_urlpatterns)),
]

gob/jobs/models.py
from django.db import models
from django.contrib.auth.models import User

from gob.utils import TimeStampMixin


class Job(TimeStampMixin):
    title = models.CharField(max_length=80, null=True)
    description = models.TextField(max_length=300)
    company_name = models.CharField(max_length=80, null=True)
    location = models.CharField(max_length=80)
    email = models.EmailField(max_length=300, null=True)
    salary_start = models.PositiveIntegerField()
    salary_end = models.PositiveIntegerField(null=True)
    status = models.BooleanField(default=True)
    message_url = models.URLField()

    added_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return F"{self.id} - {self.description[:10]}"

gob/jobs/forms.py
from django import forms
from django.forms import ModelForm

from gob.jobs.models import Job


class JobCreateForm(ModelForm):
    company_name = forms.CharField(required=False, max_length=20)
    email = forms.EmailField(required=False, max_length=300)
    location = forms.CharField(required=True, max_length=20)
    description = forms.CharField(required=True, max_length=160)
    salary_end = forms.IntegerField(required=False)

    def clean(self):
        cleaned_data = super().clean()
        if self.errors:
            return cleaned_data
        salary_start = cleaned_data['salary_start']
        salary_end = cleaned_data.get('salary_end')
        if salary_end and salary_end < salary_start:
            raise forms.ValidationError(
                "Invalid salary range",
                code='invalid_salary',
            )
        return cleaned_data

    class Meta:
        model = Job
        fields = ['company_name', 'description', 'location', 'salary_start',
                  'salary_end', 'email']


class JobUpdateForm(JobCreateForm):

    class Meta:
        model = Job
        fields = ['company_name', 'description', 'location', 'salary_start',
                  'salary_end', 'status', 'email']

gob/jobs/views.py
from django.views.generic import ListView, UpdateView
from django.views.generic.edit import CreateView
from django.conf import settings
from django.http import HttpResponseBadRequest

from gob.jobs.models import Job
from gob.jobs.forms import JobCreateForm, JobUpdateForm


class JobListView(ListView):
    model = Job

    def get_queryset(self):
        return super().get_queryset().filter(status=True).order_by(
            '-updated_on')


# List jobs by the current logged in user
class JobUserListView(ListView):
    model = Job

    def get_queryset(self):
        return super().get_queryset().filter(added_by=self.request.user)


class JobCreateView(CreateView):
    model = Job
    form_class = JobCreateForm
    success_url = '/'
    template_name = 'jobs/job_form_create.html'

    def form_valid(self, form):
        message_url = self._get_message_url()
        if not message_url:
            m = 'Something went wrong, contact site admin'
            return HttpResponseBadRequest(m)
        form.instance.message_url = message_url
        form.instance.added_by = self.request.user
        return super().form_valid(form)

    def _get_message_url(self):
        user_social_account = None
        for social_account in self.request.user.socialaccount_set.all():
            if social_account.provider == settings.OAUTH_LOGIN_PROVIDER:
                user_social_account = social_account
        if not user_social_account:
            return
        if social_account.provider == 'slack':
            uid = social_account.extra_data['user']['id']
            return F"https://{settings.SLACK_TEAM_SLUG}.slack.com/messages/{uid}"  # noqa
        elif social_account.provider == 'reddit':
            uid = self.request.user.username
            return F"https://www.reddit.com/message/compose/?to={uid}"
        else:
            return


class JobUpdateView(UpdateView):
    model = Job
    form_class = JobUpdateForm
    success_url = '/'
    template_name = 'jobs/job_form_update.html'

    def get_queryset(self):
        return super().get_queryset().filter(added_by=self.request.user)

gob/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Job Board</title>
    <meta name="description" content="A very simple job board">
    <meta name="keywords" content="job, job board">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css" integrity="sha256-2k1KVsNPRXxZOsXQ8aqcZ9GOOwmJTMoOB5o5Qp1d6/s=" crossorigin="anonymous" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <style type="text/css">
      .job-description strong {
        font-weight: 500;
      }
      .job-description code {
        background-color: #FFFFFF;
        color: #000000;
      }
    </style>
</head>
<body>

  <nav class="navbar is-link">
    <div class="navbar-brand">
      <a class="navbar-item" href="/"><i class="fas fa-home"></i></a>
    </div>
    <div class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          {% if user.is_authenticated %}
          <p class="control">
            <a class="button is-white" href="{% url 'jobs:add' %}">Add</a>
          </p>
          <p class="control">
            <a class="button is-white" href="{% url 'jobs:self' %}">Self</a>
          </p>
          {% else %}
          <p class="control">
            <a class="button is-white" href="{% url 'jobs:login' %}">Login</a>
          </p>
          {% endif %}
          <p class="control">
            <a class="button is-white" href="//github.com/avinassh/gob"><i class="fab fa-github"></i></a>
          </p>
        </div>
      </div>
    </div>
  </div>
</nav>
 <br>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>

gob/templates/jobs/job_form_create.html
{% extends "base.html" %}

{% block content %}
<form method="post">
  {% include "jobs/job_form_fields.html" %}
  <div class="field">
  <div class="control">
    <button class="button is-link">Submit</button>
  </div>
  </div>
</form>
{% endblock %}

gob/templates/jobs/job_form_fields.html
  {% if form.errors %}
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <p class="help is-danger">{{ error }}</p>
    {% endfor %}
    {% endif %}
  {% endif %}
  {% csrf_token %}
  <div class="field">
    <label class="label" for="id_company_name">Company Name</label>
    <div class="control">
      <input class="input" id="id_company_name" name="company_name" type="text" maxlength="20" placeholder="(Optional) Name of the company" value="{{ form.company_name.value|default_if_none:'' }}">
    </div>
  </div>
  <div class="field">
    <label class="label" for="id_description">Description</label>
    <div class="control">
      <textarea class="textarea" id="id_description" name="description" maxlength="160" placeholder="Enter job description (supports markdown)" required>{{ form.description.value|default_if_none:'' }}</textarea>
    </div>
  </div>
  <div class="field">
    <label class="label" for="id_location">Location</label>
    <div class="control">
      <input class="input" id="id_location" name="location" type="text" maxlength="20" value="{{ form.location.value|default_if_none:'' }}" placeholder="Where it is located? or enter remote" required>
    </div>
  </div>
  <div class="field">
    <label class="label" for="id_salary_start">Salary Range</label>
    <div class="control">
      <input class="input" id="id_salary_start" name="salary_start" type="number" value="{{ form.salary_start.value }}" placeholder="Enter (yearly) salary or start range" required>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <input class="input" id="id_salary_end" name="salary_end" type="number" value="{{ form.salary_end.value }}" placeholder="(Optional) Enter salary end range">
    </div>
  </div>
  <div class="field">
    <label class="label" for="id_email">Email</label>
    <div class="control">
      <input class="input" id="id_email" name="email" type="email" maxlength="300" placeholder="(Optional) Your contact email" value="{{ form.email.value|default_if_none:'' }}">
    </div>
  </div>

gob/templates/jobs/job_form_update.html
{% extends "base.html" %}

{% block content %}
<form method="post">
  {% include "jobs/job_form_fields.html" %}
  <div class="field">
    <label class="label" for="id_status">Status: <input type="checkbox" name="status" id="id_status" {% if form.status.value %}checked{% endif %}></label>
    <p class="help is-danger">Unchecking will result in unlisting the job</p>
  </div>
  <div class="field">
    <div class="control">
      <button class="button is-link">Submit</button>
    </div>
  </div>
</form>
{% endblock %}

gob/templates/jobs/job_list.html
{% extends "base.html" %}
{% load md2 %}
{% block content %}
<div class="tile is-ancestor">
  {% for job in object_list %}
  <div class="tile is-parent">
    <article class="tile is-child box{% if not job.status %} notification is-grey{% endif %}">
      <div class="content job-description">
        {{ job.description|markdown:"safe" }}
      </div>
      <p>&#8377;{{ job.salary_start }}{% if job.salary_end %} - &#8377;{{ job.salary_end }}{% endif %}{% if job.company_name %} | <i class="fas fa-building"></i> {{ job.company_name|title }}{% endif %} | <i class="fas fa-map-marker-alt"></i> {{ job.location|title }} | <a href="{{ job.message_url }}"><i class="fas fa-envelope"></i></a>{% if job.email %} | <a href="mailto:{{ job.email }}"><i class="fas fa-at"></i></a>{% endif %}{% if job.added_by == user %} | <a href="{% url 'jobs:edit' job.id %}"><i class="fas fa-edit"></i></a>{% endif %}
      </p>
    </article>
  </div>
  {% if forloop.counter|divisibleby:3 %}
  </div>
  <div class="tile is-ancestor">
  {% endif %}
  {% empty %}
    <p>You have not posted any jobs.</p>
  {% endfor %}
</div>
{% endblock %}